editors:
   #  - version: 2019.1
  - version: 2018.3
  #- version: trunk
platforms:
  - name: win
    type: Unity::VM
    image: sdet/gamecode_win10:v0.2.1-91595
    flavor: m1.large
    
---
{% for editor in editors %}
{% for platform in platforms %}
{{ platform.name }}_{{ editor.version }}:
  name : Build and Test version {{ editor.version }} on {{ platform.name }}
  agent:
    type: {{ platform.type }}
    image: {{ platform.image }}
    flavor: {{ platform.flavor}}
  commands:
    - |
      source ~/.bash_profile; source /etc/profile;
      unset UPM_CACHE_PATH; unset UPM_NPM_CACHE_PATH;
      build.cmd
      #git clone --single-branch --branch jasons/pai-423_fails_on_mac_vm git@gitlab.cds.internal.unity3d.com:upm-packages/project-templates/upm-template-utils.git 
      npm install upm-ci-utils --registry https://api.bintray.com/npm/unity/unity-npm
      #npm install upm-template-utils
      #node upm-template-utils/index.js package pack --package-path com.unity.canary-package
      #node upm-template-utils/index.js package test --unity-version {{ editor.version }} --package-path com.unity.canary-package
      upm-ci package pack --package-path build/install/com.unity.formats.alembic
      upm-ci package test --unity-version {{ editor.version }} --package-path build/install/com.unity.formats.alembic
      #triggers:
      #branches:
      #only:
      #  - master
  artifacts:
    UTR_Output.zip:
      paths:
        - "utr_output/**/*"
{% endfor %}
{% endfor %}

run_preview_production:
  name: Preview Package to Production
  agent:
    type: Unity::VM
    image: package-ci/win10:latest
    flavor: m1.large
    name: Runner
  commands:
    # Install ci tools dependencies
    - npm install upm-ci-utils -g --registry https://api.bintray.com/npm/unity/unity-npm
    - upm-ci package pack --package-path .
    - upm-ci package publish --registry staging --package-path .
  triggers:
    tags:
      only:
        - /^(p|P)ublish (v|V)[0-9].[0-9].[0-9]-(p|P)review/
  artifacts:
    Package.zip:
      paths:
        - "automation/package/*.tgz"
  dependencies:
  {% for editor in editors %}
  {% for platform in platforms %}
    - .yamato/build.yml#{{ platform.name }}_{{ editor.version }}
  {% endfor %}  
  {% endfor %}

run_verified_production:
  name: Verified Package to Production
  agent:
    type: Unity::VM
    image: package-ci/win10:latest
    flavor: m1.large
    name: Runner
  commands:
    - echo "We do not support publishing verified packages to production at this time"
  triggers:
    tags:
      only:
        - /^(p|P)ublish (v|V)[0-9].[0-9].[0-9]$/
  artifacts:
    Package.zip:
      paths:
        - "automation/package/*.tgz"
  dependencies:
  {% for editor in editors %}
  {% for platform in platforms %}
    - .yamato/build.yml#{{ platform.name }}_{{ editor.version }}
  {% endfor %}  
  {% endfor %}
